name: Claimz
version: '${project.version}'
main: me.mimovnik.claimz.Claimz
api-version: 1.19
authors: [ Mimovnik ]
description: Allow players to claim land where you cannot be griefed.
commands:
  deleteClaim:
    description: Deletes the claim a sender is currently standing in.
    usage: /<command> <- without any arguments
  toggleShowClaims:
    description: Toggles the display of nearby claims.
    usage: /<command> <- without any arguments
  giveCubes:
    description: Gives certain amount of cubes to a sender
    usage: /<command> amount
  toggleGuardClaims:
    description: Toggles the guard of all claims.
    usage: /<command> <- without any arguments