name: Claimz
version: '${project.version}'
main: me.mimovnik.claimz.Claimz
api-version: 1.19
authors: [ Mimovnik ]
description: Allow players to claim land where you cannot be griefed.
commands:
  deleteClaim:
    description: Deletes the claim the sender is currently standing in.
    usage: /<command>
  toggleShowClaims:
    description: Toggles the display of nearby claims.
    usage: /<command>
  giveCubes:
    description: Gives certain amount of cubes to a sender
    usage: /<command> [amount]
  toggleGuardClaims:
    description: Toggles the guard of all claims.
    usage: /<command>
  trust:
    description: Grants a player access to the claim the sender is currently standing in.
    usage: /<command> [player]
  distrust:
    description: Removes access from a player to the claim the sender is currently standing in.
    usage: /<command> [player]
  showTrusted:
    description: Lists trusted players of the claim the sender is currently standing in.
    usage: /<command>